name: sprawozdanie_pdf
on: push
jobs:
  sprawozdanie:
    runs-on: ubuntu-22.04
    steps: 
      - run: sudo apt-get update
      - run: sudo apt-get install texlive-xetex inkscape pandoc
      - uses: actions/checkout@v4
      - run: pip install pint open-atmos-jupyter-utils scipy nbconvert ipykernel
      - run: python -m nbconvert --to pdf --execute lab3.ipynb checkout --output sprawozdanie3.pdf
      - uses: actions/upload-artifact@v4
        with:
          path: sprawozdanie3.pdf

